app = 'lens-schedule'
primary_region = 'iad'

[build]
  # O Fly.io deteta o Dockerfile automaticamente se ele estiver presente na raiz

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']